version: '3.8'

services:
  server:
    build: apps/server
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/research-hub?schema=public
    
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: research-hub
    volumes:
      - ./apps/server/db_data:/var/lib/postgresql/data