import { SeedGroupService } from '../service/seed-group/seed-group.service';

export const getMembersAtPeriodData: Awaited<
  ReturnType<typeof SeedGroupService.prototype.getMembersAtPeriod>
> = [
  {
    affiliationDate: new Date(),
    functions: ['', '', ''],
    id: 1,
    isActive: true,
    memberId: 1,
    period: '2023-1',
    seedGroupId: 1,
    role: 'Student',
    Member: {
      id: 1,
      name: 'Member 1',
      email: '',
      identityCard: '',
      institutionalCode: '',
    },
  },
  {
    affiliationDate: new Date(),
    functions: ['', '', ''],
    id: 2,
    isActive: true,
    memberId: 2,
    period: '2023-1',
    seedGroupId: 1,
    role: 'Professor',
    Member: {
      id: 2,
      name: 'Member 2',
      email: '',
      identityCard: '',
      institutionalCode: '',
    },
  },
  {
    affiliationDate: new Date(),
    functions: ['', '', ''],
    id: 3,
    isActive: true,
    memberId: 3,
    period: '2022-1',
    seedGroupId: 1,
    role: 'Student',
    Member: {
      id: 3,
      name: 'Member 3',
      email: '',
      identityCard: '',
      institutionalCode: '',
    },
  },
  {
    affiliationDate: new Date(),
    functions: ['', '', ''],
    id: 4,
    isActive: true,
    memberId: 4,
    period: '2022-1',
    seedGroupId: 1,
    role: 'Student',
    Member: {
      id: 4,
      name: 'Member 4',
      email: '',
      identityCard: '',
      institutionalCode: '',
    },
  },
  {
    affiliationDate: new Date(),
    functions: ['', '', ''],
    id: 5,
    isActive: true,
    memberId: 5,
    period: '2022-1',
    seedGroupId: 2,
    role: 'Student',
    Member: {
      id: 5,
      name: 'Member 5',
      email: '',
      identityCard: '',
      institutionalCode: '',
    },
  },
  {
    affiliationDate: new Date(),
    functions: ['', '', ''],
    id: 6,
    isActive: true,
    memberId: 6,
    period: '2022-1',
    seedGroupId: 2,
    role: 'Student',
    Member: {
      id: 6,
      name: 'Member 6',
      email: '',
      identityCard: '',
      institutionalCode: '',
    },
  },
];

export const getMembersData: Awaited<
  ReturnType<typeof SeedGroupService.prototype.getLatestMembers>
> = [
  {
    affiliationDate: new Date(),
    functions: ['', '', ''],
    id: 1,
    isActive: true,
    memberId: 1,
    period: '2023-1',
    seedGroupId: 1,
    role: 'Student',
    Member: {
      id: 1,
      name: 'Member 1',
      email: '',
      identityCard: '',
      institutionalCode: '',
    },
  },
  {
    affiliationDate: new Date(),
    functions: ['', '', ''],
    id: 2,
    isActive: true,
    memberId: 2,
    period: '2023-1',
    seedGroupId: 1,
    role: 'Professor',
    Member: {
      id: 2,
      name: 'Member 2',
      email: '',
      identityCard: '',
      institutionalCode: '',
    },
  },
  {
    affiliationDate: new Date(),
    functions: ['', '', ''],
    id: 3,
    isActive: true,
    memberId: 3,
    period: '2023-1',
    seedGroupId: 1,
    role: 'Student',
    Member: {
      id: 3,
      name: 'Member 3',
      email: '',
      identityCard: '',
      institutionalCode: '',
    },
  },
];
